---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pulumi-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/yaml
  prune: false
  sourceRef:
    kind: GitRepository
    name: pulumi-operator-repo
  targetNamespace: default

